/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import javax.swing.JOptionPane;
import Controlador.*;
        
/**
 *
 * @author Usuario
 */
public class Menu_Gerente extends javax.swing.JFrame {
    String usuario;
    ControlEmpleado controlUsuario = new ControlEmpleado();
    /**
     * Creates new form Menu_Principal
     */
    public Menu_Gerente(String usuario) {
        this.usuario = usuario;
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(0);
        cargarDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButtonAgreagarEmpleado = new javax.swing.JButton();
        jButtonConsultarEmpleado = new javax.swing.JButton();
        jButtonModificarEmpleado = new javax.swing.JButton();
        jButtonEliminarEmpleado = new javax.swing.JButton();
        activarE = new javax.swing.JButton();
        slide = new diu.swe.habib.JPanelSlider.JPanelSlider();
        letrero = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        perfil = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        idSede = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(128, 49, 145));
        jLabel17.setText("Consultar");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

        jLabel18.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(128, 49, 145));
        jLabel18.setText("Modificar");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, -1));

        jLabel19.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(128, 49, 145));
        jLabel19.setText("Eliminar");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(128, 49, 145));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 530, 20));

        jLabel20.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(128, 49, 145));
        jLabel20.setText("Empleados:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel21.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(128, 49, 145));
        jLabel21.setText("Agregar");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jButtonAgreagarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAgreagarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregarUsuario.png"))); // NOI18N
        jButtonAgreagarEmpleado.setBorder(null);
        jButtonAgreagarEmpleado.setBorderPainted(false);
        jButtonAgreagarEmpleado.setContentAreaFilled(false);
        jButtonAgreagarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAgreagarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgreagarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAgreagarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 90, 90));

        jButtonConsultarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        jButtonConsultarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ConsultarUsuario.png"))); // NOI18N
        jButtonConsultarEmpleado.setBorder(null);
        jButtonConsultarEmpleado.setBorderPainted(false);
        jButtonConsultarEmpleado.setContentAreaFilled(false);
        jButtonConsultarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConsultarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonConsultarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 90, 90));

        jButtonModificarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        jButtonModificarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modificarUsuario.png"))); // NOI18N
        jButtonModificarEmpleado.setBorder(null);
        jButtonModificarEmpleado.setBorderPainted(false);
        jButtonModificarEmpleado.setContentAreaFilled(false);
        jButtonModificarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModificarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 90, 90));

        jButtonEliminarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEliminarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eliminarUsuario.png"))); // NOI18N
        jButtonEliminarEmpleado.setBorder(null);
        jButtonEliminarEmpleado.setBorderPainted(false);
        jButtonEliminarEmpleado.setContentAreaFilled(false);
        jButtonEliminarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 90, 90));

        activarE.setBackground(new java.awt.Color(255, 255, 255));
        activarE.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        activarE.setForeground(new java.awt.Color(128, 49, 145));
        activarE.setText("Activar empleados");
        activarE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        activarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activarEActionPerformed(evt);
            }
        });
        jPanel1.add(activarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 300, 35));

        letrero.setBackground(new java.awt.Color(38, 39, 38));
        letrero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setBackground(new java.awt.Color(250, 250, 250));
        jLabel25.setFont(new java.awt.Font("Decker", 1, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Gerente");
        letrero.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 180, 50));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoXYZ.png"))); // NOI18N
        letrero.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, 110));

        jButton1.setBackground(new java.awt.Color(38, 39, 38));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tuperfil.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        letrero.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 32, 32));

        slide.add(letrero, "card2");

        perfil.setBackground(new java.awt.Color(38, 39, 38));
        perfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(38, 39, 38));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/volver.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        perfil.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 32, 32));

        jLabel27.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("NOMBRE");
        perfil.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, -1));

        nombre.setEditable(false);
        nombre.setBackground(new java.awt.Color(38, 39, 38));
        nombre.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setBorder(null);
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        perfil.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 140, -1));

        jLabel31.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("N° SEDE");
        perfil.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 80, 20));

        idSede.setEditable(false);
        idSede.setBackground(new java.awt.Color(38, 39, 38));
        idSede.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        idSede.setForeground(new java.awt.Color(255, 255, 255));
        idSede.setBorder(null);
        perfil.add(idSede, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 160, -1));

        jLabel32.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("TELEFONO");
        perfil.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 80, -1));

        telefono.setEditable(false);
        telefono.setBackground(new java.awt.Color(38, 39, 38));
        telefono.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        telefono.setForeground(new java.awt.Color(255, 255, 255));
        telefono.setBorder(null);
        perfil.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 160, -1));

        jLabel33.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("CEDULA");
        perfil.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, -1));

        cedula.setEditable(false);
        cedula.setBackground(new java.awt.Color(38, 39, 38));
        cedula.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        cedula.setForeground(new java.awt.Color(255, 255, 255));
        cedula.setBorder(null);
        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });
        perfil.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 140, -1));

        jButton3.setBackground(new java.awt.Color(38, 39, 38));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logOut.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        perfil.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 32, 32));
        perfil.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 160, 10));
        perfil.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 62, 130, 0));
        perfil.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 140, 10));
        perfil.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 140, 10));
        perfil.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 160, 10));

        slide.add(perfil, "card3");

        jPanel1.add(slide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarDatos(){
        String consulta[] = controlUsuario.consultarUsuario(usuario);
        this.nombre.setText(consulta[3]);
        this.cedula.setText(consulta[0]);
        this.idSede.setText(consulta[8]);
        this.telefono.setText(consulta[9]);
    }
    private void jButtonEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarEmpleadoActionPerformed
        eliminarUsuario e = new eliminarUsuario(usuario);
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonEliminarEmpleadoActionPerformed

    private void jButtonModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarEmpleadoActionPerformed
        modificarUsuario e = new modificarUsuario(usuario);
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonModificarEmpleadoActionPerformed

    private void jButtonAgreagarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgreagarEmpleadoActionPerformed
        agregarEmpleado g = new agregarEmpleado(usuario);
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAgreagarEmpleadoActionPerformed

    private void jButtonConsultarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarEmpleadoActionPerformed
        ConsultarEmpleado g = new ConsultarEmpleado(usuario);
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonConsultarEmpleadoActionPerformed

    private void activarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activarEActionPerformed
        ActivarEmpleado g = new ActivarEmpleado(usuario);
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_activarEActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        slide.nextPanel(20, perfil, slide.left);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        slide.nextPanel(20, letrero, slide.right);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed

    }//GEN-LAST:event_nombreActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        login U = new login();
        this.setVisible(false);
        U.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activarE;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField idSede;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAgreagarEmpleado;
    private javax.swing.JButton jButtonConsultarEmpleado;
    private javax.swing.JButton jButtonEliminarEmpleado;
    private javax.swing.JButton jButtonModificarEmpleado;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel letrero;
    private javax.swing.JTextField nombre;
    private javax.swing.JPanel perfil;
    private diu.swe.habib.JPanelSlider.JPanelSlider slide;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
