/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import Controlador.ControlEmpleado;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Vendedor extends javax.swing.JFrame {
    String usuario;
    ControlEmpleado controlUsuario = new ControlEmpleado();
    /**
     * Creates new form Vendedor
     */
    public Vendedor(String usuario) {
        this.usuario = usuario;
        initComponents();
        setDefaultCloseOperation(0);
        this.setLocationRelativeTo(null);
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        AgregarFacturacion = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ConsultarFacturacion = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        EliminarFacturacion = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        AgregarCotizacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ConsultarCotizacion = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        EliminarCotizacion = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        slide = new diu.swe.habib.JPanelSlider.JPanelSlider();
        letrero = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        perfil = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        idSede = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregarFacturacion.setBackground(new java.awt.Color(250, 250, 250));
        AgregarFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgregarFactura.png"))); // NOI18N
        AgregarFacturacion.setBorder(null);
        AgregarFacturacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AgregarFacturacion.setPreferredSize(new java.awt.Dimension(90, 90));
        AgregarFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarFacturacionActionPerformed(evt);
            }
        });
        jPanel4.add(AgregarFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 90, 90));

        jLabel13.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(128, 49, 145));
        jLabel13.setText("Facturacion:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 49, 145));
        jLabel7.setText("Agregar");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        ConsultarFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ConsultarFacturacion.png"))); // NOI18N
        ConsultarFacturacion.setBorder(null);
        ConsultarFacturacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConsultarFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarFacturacionActionPerformed(evt);
            }
        });
        jPanel4.add(ConsultarFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 90, 90));

        jLabel8.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(128, 49, 145));
        jLabel8.setText("Consultar");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, -1, -1));

        EliminarFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EliminarPlantilla.png"))); // NOI18N
        EliminarFacturacion.setBorder(null);
        EliminarFacturacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EliminarFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarFacturacionActionPerformed(evt);
            }
        });
        jPanel4.add(EliminarFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 90, 90));

        jLabel10.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(128, 49, 145));
        jLabel10.setText("Eliminar");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(128, 49, 145));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 530, 20));

        jLabel14.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(128, 49, 145));
        jLabel14.setText("Cotizacion:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        AgregarCotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgregarFactura.png"))); // NOI18N
        AgregarCotizacion.setBorder(null);
        AgregarCotizacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AgregarCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCotizacionActionPerformed(evt);
            }
        });
        jPanel4.add(AgregarCotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 90, 90));

        jLabel1.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(128, 49, 145));
        jLabel1.setText("Agregar");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        ConsultarCotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ConsultarFacturacion.png"))); // NOI18N
        ConsultarCotizacion.setBorder(null);
        ConsultarCotizacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConsultarCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarCotizacionActionPerformed(evt);
            }
        });
        jPanel4.add(ConsultarCotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 90, 90));

        jLabel16.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(128, 49, 145));
        jLabel16.setText("Consultar");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        EliminarCotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EliminarPlantilla.png"))); // NOI18N
        EliminarCotizacion.setBorder(null);
        EliminarCotizacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EliminarCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCotizacionActionPerformed(evt);
            }
        });
        jPanel4.add(EliminarCotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 90, 90));

        jLabel18.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(128, 49, 145));
        jLabel18.setText("Eliminar");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));

        letrero.setBackground(new java.awt.Color(38, 39, 38));
        letrero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(250, 250, 250));
        jLabel11.setFont(new java.awt.Font("Decker", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Vendedor");
        letrero.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 180, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoXYZ.png"))); // NOI18N
        letrero.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, 110));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tuperfil.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        letrero.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 32, 32));

        slide.add(letrero, "card2");

        perfil.setBackground(new java.awt.Color(38, 39, 38));
        perfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(38, 39, 38));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/volver.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        perfil.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 30, 32));

        jLabel27.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("NOMBRE");
        perfil.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, -1));

        nombre.setEditable(false);
        nombre.setBackground(new java.awt.Color(38, 39, 38));
        nombre.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setBorder(null);
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        perfil.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 140, -1));

        jLabel31.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("N° SEDE");
        perfil.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 80, 20));

        idSede.setEditable(false);
        idSede.setBackground(new java.awt.Color(38, 39, 38));
        idSede.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        idSede.setForeground(new java.awt.Color(255, 255, 255));
        idSede.setBorder(null);
        perfil.add(idSede, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 160, -1));

        jLabel32.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("TELEFONO");
        perfil.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 80, -1));

        telefono.setEditable(false);
        telefono.setBackground(new java.awt.Color(38, 39, 38));
        telefono.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        telefono.setForeground(new java.awt.Color(255, 255, 255));
        telefono.setBorder(null);
        perfil.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 160, -1));

        jLabel33.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("CEDULA");
        perfil.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, -1));

        cedula.setEditable(false);
        cedula.setBackground(new java.awt.Color(38, 39, 38));
        cedula.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        cedula.setForeground(new java.awt.Color(255, 255, 255));
        cedula.setBorder(null);
        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });
        perfil.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 140, -1));

        jButton5.setBackground(new java.awt.Color(38, 39, 38));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logOut.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        perfil.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 32, 32));
        perfil.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 160, 10));
        perfil.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 62, 130, 0));
        perfil.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 140, 10));
        perfil.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 140, 10));
        perfil.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 160, 10));

        slide.add(perfil, "card3");

        jPanel4.add(slide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void cargarDatos(){
        String consulta[] = controlUsuario.consultarUsuario(usuario);
        this.nombre.setText(consulta[3]);
        this.cedula.setText(consulta[0]);
        this.idSede.setText(consulta[8]);
        this.telefono.setText(consulta[9]);
    }
    private void ConsultarCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarCotizacionActionPerformed
        consultarCotizacion u = new consultarCotizacion(usuario);
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ConsultarCotizacionActionPerformed

    private void AgregarCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCotizacionActionPerformed
        agregarCotizacion agregarCotizacion = new agregarCotizacion(usuario);
        agregarCotizacion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AgregarCotizacionActionPerformed

    private void AgregarFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarFacturacionActionPerformed
        String sede = this.idSede.getText();
        agregarVenta agregarVenta = new agregarVenta(usuario, sede);
        agregarVenta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AgregarFacturacionActionPerformed

    private void ConsultarFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarFacturacionActionPerformed
        consultarVenta u = new consultarVenta(usuario);
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ConsultarFacturacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        slide.nextPanel(20, perfil, slide.left);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        slide.nextPanel(20, letrero, slide.right);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed

    }//GEN-LAST:event_nombreActionPerformed

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        login U = new login();
        this.setVisible(false);
        U.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void EliminarFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarFacturacionActionPerformed
        eliminarVenta u = new eliminarVenta(usuario);
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EliminarFacturacionActionPerformed

    private void EliminarCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCotizacionActionPerformed
        eliminarCotizacion u = new eliminarCotizacion(usuario);
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EliminarCotizacionActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCotizacion;
    private javax.swing.JButton AgregarFacturacion;
    private javax.swing.JButton ConsultarCotizacion;
    private javax.swing.JButton ConsultarFacturacion;
    private javax.swing.JButton EliminarCotizacion;
    private javax.swing.JButton EliminarFacturacion;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField idSede;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel letrero;
    private javax.swing.JTextField nombre;
    private javax.swing.JPanel perfil;
    private diu.swe.habib.JPanelSlider.JPanelSlider slide;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
